apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app.kubernetes.io/name: sausage-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  vault_token: {{ .Values.vaultToken | b64enc }}
