apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: sausage-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
