stages:
  - release

helm-release:
  stage: release
  image: alpine/k8s:1.22.6
  script:
    - mkdir -p ~/.kube
    - echo "$kubeconfig" | base64 -d > ~/.kube/config
    - cp ~/.kube/config ./kubeconfig
    - helm upgrade --install pelmennaya ./infrastructure/helm \
        --namespace default \
        --create-namespace \
        --kubeconfig ./kubeconfig \
        --set global.backend.AppVersion=$VERSION \
        --set global.frontend.AppVersion=$VERSION
