apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    route:
      receiver: "telegram"
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m
      routes:
        - receiver: "telegram"
          match_re:
            severity: critical|warning
          continue: true

    receivers:
      - name: "telegram"
        telegram_configs:
          - send_resolved: true
            bot_token: '5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs'
            chat_id: -1002332977243
            api_url: "https://api.telegram.org"
            message: |
              🔥 *Alert {{"{{ .Status }}"}}!* 🔥

              {{" {{ range .Alerts }}"}}
              *Alert:*{{" {{ .Labels.alertname }}"}}
              *Status:* {{"{{ $.Status }}"}}
              *Severity:* {{"{{ .Labels.severity }}"}}
              *Project:* {{"{{ .Labels.project }}"}}
              *Component:* {{"{{ .Labels.component }}"}}

              {{"{{- if .Annotations.summary }}"}}
              *Summary:* {{"{{ .Annotations.summary }}"}}
              {{"{{- end }}"}}
              {{"{{- if .Annotations.description }}"}}
              *Description:* {{"{{ .Annotations.description }}"}}
              {{"{{- end }}"}}
              {{"{{ end }}"}}
