stages:
  - build
  - notify

build-frontend-code-job:
  stage: build
  rules:
    - changes:
      - frontend/**/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
    - frontend/dist/frontend

telegram-notification-frontend:
  stage: notify
  rules:
    - changes:
       - frontend/**/*
    - if: '$CI_COMMIT_MESSAGE =~ /send notification/'
  script:
     - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002332977243\", \"text\": \"Гладких Данил собрал Frontend $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$CI_JOB_NAME\"}" https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage'
  needs:
    - build-frontend-code-job      
