build-frontend-code-job:
  stage: build
  rules:
    - changes:
      - frontend/**/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
    - frontend/dist/frontend

variables:
  SONAR_LOGIN: "69fa85d8af0f098547ba1ef03678d65d3d421324"

sonarqub-frontend-sast:
  stage: test
  rules:
    - changes:
      - frontend/**/*
  image: sonarsource/sonar-scanner-cli
  needs: 
    - build-frontend-code-job
  script:
    sonar-scanner -X
    -Dsonar.projectKey=$SONAR_PROJECT_KEY_FRONT
    -Dsonar.sources=.
    -Dsonar.host.url=$SONARQUBE_URL
    -Dsonar.login=$SONAR_LOGIN
    -Dsonar.exclusions=**/*.java

telegram-notification-frontend:
  stage: notify
  rules:
    - changes:
       - frontend/**/*
    - if: '$CI_COMMIT_MESSAGE =~ /send notification/'
  script:
     - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002332977243\", \"text\": \"Гладких Данил собрал Frontend $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$CI_JOB_NAME\"}" https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage'
  needs:
    - build-frontend-code-job      
