stages:
  - build
  - release

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/frontend"

build-frontend:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm run build
    - mv dist public
    - cp nginx.conf public/
  artifacts:
    paths:
      - frontend/public/
  tags:
    - kubernetes

kaniko-build-frontend:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: /kaniko/.docker/
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cp -r frontend/public frontend/ 
    - /kaniko/executor
        --context $CI_PROJECT_DIR/frontend
        --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile
        --destination $IMAGE_NAME:$VERSION
        --destination $IMAGE_NAME:latest
  tags:
    - kubernetes
  needs: [build-frontend]
