stages:
  - build
  - release
  
variables:
  VERSION: 1.0.1

build-frontend:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm run build
    - mv dist public
    - cp nginx.conf public/
  artifacts:
    paths:
      - frontend/public/
  tags:
    - kubernetes

docker-build-frontend:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest frontend
    - docker push $IMAGE_NAME:$VERSION
    - docker push $IMAGE_NAME:latest
  needs: [build-frontend]
  tags:
    - kubernetes
