stages:
  - test
  - build
  - release
  
variables:
  VERSION: 1.0.12
  

sonarqube-frontend:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner \
        -Dsonar.projectKey=gladkiklhpelmen_frontend \
        -Dsonar.sources=./frontend \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN_FRONTEND
  tags:
    - kubernetes

build-frontend:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm run build
    - mv dist public
    - cp nginx.conf public/
  artifacts:
    paths:
      - frontend/public/
  tags:
    - kubernetes

docker-build-frontend:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$VERSION -t $CI_REGISTRY_IMAGE/frontend:latest frontend
    - docker push $CI_REGISTRY_IMAGE/frontend:$VERSION
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  needs: [build-frontend]
  tags:
    - kubernetes
