variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release
  - deploy

build:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm run build
    - mv dist public_html
    - cp nginx.conf public_html/
  artifacts:
    paths:
      - frontend/public_html/
  rules:
    - changes:
        - frontend/**/*

docker-release:
  stage: release
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$VERSION frontend/
    - docker push $CI_REGISTRY_IMAGE/frontend:$VERSION  
        
        
      

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  script:
    - mkdir -p ~/.kube
    - echo "$kubeconfig" | base64 -d > ~/.kube/config
    - helm upgrade --install pelmennaya-frontend infrastructure/helm/charts/frontend --set image.tag=$VERSION
  rules:
    - changes:
        - frontend/**/*
      when: manual
