stages:
  - build
  - release

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-frontend-image:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm run build
    - mv dist public_html
    - cp nginx.conf public_html/
  tags:
    - kubernetes

docker-push-frontend:
  stage: release
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - cp -r frontend/public_html frontend/  # или подкорректируй Dockerfile
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$VERSION frontend/
    - docker push $CI_REGISTRY_IMAGE/frontend:$VERSION
  needs: [build-frontend-image]
  tags:
    - kubernetes
