stages:
  - build
  - release

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/frontend"

build-frontend:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm ci
    - npm run build
    - mv dist public
    - cp nginx.conf public/
  artifacts:
    paths:
      - frontend/public/
  tags:
    - kubernetes

docker-build-frontend:
  stage: release
  image: docker:20.10.12-dind-rootless
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cp -r frontend/public frontend/
    - docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest frontend
    - docker push $IMAGE_NAME:$VERSION
    - docker push $IMAGE_NAME:latest
  needs: [build-frontend]
  tags:
    - kubernetes
