apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  namespace: std-ext-014-39
  labels:
    app: backend-report
spec:
  revisionHistoryLimit: 12
  replicas: 2
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - backend-report
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-ext-014-39/sausage-store-report:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: VAULT_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: VAULT_HOST
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
      imagePullSecrets:
        - name: docker-config-secret
