stages:
  - trigger

check-changes:
  stage: trigger
  script:
    - echo "Checking which part of the project has changed..."
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -qE '^backend/'; then
        echo "BACKEND_CHANGED=true" >> variables.env
      fi
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -qE '^frontend/'; then
        echo "FRONTEND_CHANGED=true" >> variables.env
      fi
  artifacts:
    reports:
      dotenv: variables.env

trigger-backend:
  stage: trigger
  needs: ["check-changes"]
  rules:
    - if: '$BACKEND_CHANGED == "true"'
  trigger:
    include: "backend/.gitlab-ci.yml"

trigger-frontend:
  stage: trigger
  needs: ["check-changes"]
  rules:
    - if: '$FRONTEND_CHANGED == "true"'
  trigger:
    include: "frontend/.gitlab-ci.yml"