stages:
  - test
  - build
  - release
  
variables:
  VERSION: 1.0.12
  
test-backend:
  stage: test
  image: golang:1.20
  script:
    - cd backend
    - go test ./...
  tags:
    - kubernetes
Для frontend (если нет тест

sonarqube-backend:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner \
        -Dsonar.projectKey=gladkiklhpelmen_backend \
        -Dsonar.sources=./backend \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN_BACKEND
  tags:
    - kubernetes
    
build-backend:
  stage: build
  image: golang:1.20
  script:
    - cd backend 
    - go build -o api ./cmd/api
    - mv api ../api-${VERSION}
  artifacts:
    paths:
      - api-${VERSION}
  tags:
    - kubernetes

docker-build-backend:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cp api-${VERSION} backend/
    - cd backend
    - docker build -t $CI_REGISTRY_IMAGE/backend:$VERSION .
    - docker push $CI_REGISTRY_IMAGE/backend:$VERSION
  needs: [build-backend]
  tags:
    - kubernetes


