stages:
  - build
  - release

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"

build-backend-image:
  stage: build
  image: golang:1.17
  script:
    - cd backend
    - go build ./cmd/api/
    - mv api ../api
    - chmod +x ../api
  tags:
    - kubernetes

docker-push-backend:
  stage: release
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375  # порт 2375, не 2376
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - cp api backend/
    - docker build -t $CI_REGISTRY_IMAGE/backend:$VERSION backend/
    - docker push $CI_REGISTRY_IMAGE/backend:$VERSION
  tags:
    - kubernetes
