stages:
  - release

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/backend"

release-backend:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE/backend:$VERSION -f backend/Dockerfile ./backend
    - docker push $CI_REGISTRY_IMAGE/backend:$VERSION
    - docker tag $CI_REGISTRY_IMAGE/backend:$VERSION $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  tags:
    - kubernetes
