stages:
  - build
  - release

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/backend"

build-backend:
  stage: build
  image: golang:1.17
  script:
    - cd backend
    - go build -o api ./cmd/api
    - mv api ../
  artifacts:
    paths:
      - api
  tags:
    - kubernetes

kaniko-build-backend:
  stage: release
  image: gcr.io/kaniko-project/executor:latest
  variables:
    DOCKER_CONFIG: /kaniko/.docker/
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cp api backend/
    - /kaniko/executor
        --context $CI_PROJECT_DIR/backend
        --dockerfile $CI_PROJECT_DIR/backend/Dockerfile
        --destination $IMAGE_NAME:$VERSION
        --destination $IMAGE_NAME:latest
  tags:
    - kubernetes
  needs: [build-backend]
