stages:
  - module-pipelines

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"

frontend:
  stage: module-pipelines
  trigger:
    include:
      - local: 'frontend/.gitlab-ci.yml'
    strategy: depend
    variables:
      VERSION: $VERSION
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - local: 'backend/.gitlab-ci.yml'
    strategy: depend
    variables:
      VERSION: $VERSION
  only:
    changes:
      - backend/**/*

helm:
  stage: module-pipelines
  trigger:
    include:
      - local: 'infrastructure/.gitlab-ci.yml'
    strategy: depend
    variables:
      VERSION: $VERSION
  needs:
    - backend
    - frontend
  only:
    changes:
      - infrastructure/helm/**/*
      - backend/**/*
      - frontend/**/*
      
