apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "http01-clusterissuer"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.fqdn }}"
      secretName: domain-name-secret
  rules:
    - host: "{{ .Values.fqdn }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
