apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-gladkikhpelmen
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: blackbox
  endpoints:
    - interval: 30s
      path: /probe
      port: http
      params:
        module: [http_2xx]
        target: [https://gladkikhpelmen.ru]
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
