---
- name: Download OpenJDK 16 archive
  get_url:
    url: "https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz"
    dest: "/tmp/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz"
    mode: '0644'

- name: Extract OpenJDK 16 archive
  unarchive:
    src: "/tmp/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Remove tar.gz file after extraction
  file:
    path: "/tmp/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz"
    state: absent

- name: Create symlink for java (set as default)
  command: ln -svf /opt/jdk-16.0.2+7/bin/java /usr/bin/java

- name: Create backend user
  user:
    name: backend
    system: yes
    shell: /bin/false
    home: /opt/backend

- name: Create backend directory
  file:
    path: /opt/backend
    state: directory
    owner: backend
    group: backend
    mode: '0755'

- name: Download backend artifact from Nexus
  get_url:
    url: "http://nexus.praktikum-services.tech/repository/std-ext-014-39-backendSS/com/yandex/practicum/devops/sausage-store/0.0.1-SNAPSHOT/sausage-store-0.0.1-20250203.135706-3.jar"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    validate_certs: no
    dest: "/opt/backend/backend.jar"
    owner: backend
    group: backend
    mode: '0644'
  register: backend_download
  until: backend_download is success
  retries: 3
  delay: 10

- name: Create systemd unit file for backend
  template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
  become: yes

- name: Reload systemd and enable backend service
  systemd:
    daemon_reload: yes
    name: backend
    enabled: yes
    state: restarted
  become: yes
